<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CaptionForge.Core\CaptionForge.Core.csproj" />
    <ProjectReference Include="..\CaptionForge.Application\CaptionForge.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="../CaptionForge.WhisperCompat/CaptionForge.WhisperCompat.csproj" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
